#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
# SOB=$(git var GIT_AUTHOR_IDENT | sed -n 's/^\(.*>\).*$/Signed-off-by: \1/p')
# grep -qs "^$SOB" "$1" || echo "$SOB" >> "$1"

# This example catches duplicate Signed-off-by lines.

if git rev-parse --verify MERGE_HEAD >/dev/null 2>&1; then
    # It's a merge commit, so skip validation
    exit 0
fi

shopt -s nocasematch                            # Case insensitive Cases 
COMMIT_MSG_FILE=$1                          # Recieve the commit message .git/COMMIT_EDITMSG

error_msg="Aborting commit. Please add JIRA Issue prefix 'PROJ-XX, ' on commit message."
commit_regex_string="([A-Z0-9]+-[0-9]+), "
if ! grep -qE "$commit_regex_string" "$COMMIT_MSG_FILE"; then
    echo "$error_msg" >&2
    echo "Exiting...." >&2
    exit 1
fi
     